Remove react-router
temando/open-api-renderer pull request #145
Opened 2017-06-27 08:07 UTC by nfour

- [x] Removed `react-router`
- [x] Reconfigured react anchor scroller to include hash always, and for the demo to be able to override configs
- [x] `hash` is now passed around instead of the `location` object

2017-06-27 12:58 UTC, brendo commented on src/containers/Base/Base.js
> +    const { hash = '', classes } = this.props
Why did I not know this was possible!

2017-06-27 13:06 UTC, brendo requested changes
I noticed with this change that the app doesn't handle with the hash changes. 

For example:

1. http://localhost:8200/?url=https://temando.github.io/open-api-renderer/petstore-open-api-v3.0.0-RC2.json#/pet/{petId}/post
2. Notice the active state in the navigation for this method
3. Scroll further down, notice the hash in the URL updates, but the active state doesn't update with it. This is also noticeable if you scroll down into the store/user tags, the left navigation doesn't "follow" along, which is a regression on the current behaviour.

2017-06-27 21:44 UTC, nfour commented on src/containers/Base/Base.js
> +    const { hash = '', classes } = this.props
haha

2017-06-27 21:45 UTC, nfour commented
Will fix that :+1:

2017-06-27 21:54 UTC, nfour commented on src/entries/demo/Demo.js
> +const hash = window.location.hash
I suspect this isnt working

2017-06-28 03:43 UTC, phlorie commented on src/containers/Base/Base.js
> +        console.log(hash, location.hash)
`console.log` should be removed

2017-06-28 04:44 UTC, nfour commented on src/containers/Base/Base.js
> +        console.log(hash, location.hash)
:ok_hand:

2017-06-28 05:54 UTC, brendo approved these changes

2017-06-28 06:12 UTC, merged