WIP: Demo textarea
temando/open-api-renderer pull request #154
Opened 2017-07-04 11:38 UTC by nfour

An input by which users can input a definition file body directly.

- [ ] Visual overlay in `Demo` for a `textarea`
- [ ] Allow `Lincoln` to accept alternative to definitionUrl, `definition`, being a body
- [ ] Refactor demo state control

2017-07-05 11:29 UTC, nfour commented
@brendo Ready for review

2017-07-05 11:32 UTC, nfour commented on src/entries/demo/Demo.js
>    render () {
I recognize this is getting bloated - not sure if worth refactoring yet.

2017-07-05 11:54 UTC, brendo reviewed
Haven't checked this out locally yet, but it LGTM.

2017-07-05 11:54 UTC, brendo commented on src/containers/Base/Base.js
> +      if (!definitionUrl) { return }
I don't think this condition can ever be true given the line above?

2017-07-05 11:54 UTC, brendo commented on src/entries/demo/Demo.js
>    render () {
Nah, let's wait until the demo is pulled away... need to try and keep velocity up while we get features in.

2017-07-05 11:54 UTC, brendo commented on src/containers/Base/Base.js
> +  fetchDefinition = async ({ definitionUrl, validate, parserType = this.state.parserType }) => {
I like the split out, thanks.

2017-07-05 11:54 UTC, brendo commented on src/lib/definitions.js
> +    definition = YAML.safeLoad(definition)
Question for another day, reckon the parser should be responsible for this? Or just be dumb and always expect a string?

2017-07-05 12:20 UTC, brendo commented on src/containers/Base/Base.js
>        <p>You can also set this with the <code>?url</code> query parameter.</p>
Guess this copy can be updated too, as there's a new way to do it ;)

2017-07-05 12:22 UTC, brendo requested changes
Minor changes to default state text and to the README to document the `definition` property required.

2017-07-05 13:19 UTC, nfour commented on src/containers/Base/Base.js
> +      if (!definitionUrl) { return }
Ha, this is why we have reviews

2017-07-05 13:51 UTC, nfour commented on src/containers/Base/Base.js
>        <p>You can also set this with the <code>?url</code> query parameter.</p>
:ok_hand:

2017-07-05 13:51 UTC, nfour commented on src/lib/definitions.js
> +    definition = YAML.safeLoad(definition)
No reason why you can't give it pre-parsed structures, for efficiency. The type check is trivial.

2017-07-06 00:26 UTC, nfour commented
@brendo feedback implimented

2017-07-06 06:41 UTC, closed without merging