Allow setting initial opened tree depth for schema visualiser.
temando/open-api-renderer pull request #158
Opened 2017-07-05 11:12 UTC by quangkhoa

Resolve #96

2017-07-05 11:39 UTC, brendo commented
Please update the README with the new property and explaining how to use it :)

Haven't test locally yet, interested to see how it behaves when attempting to collapse an auto-opened subset.

Mostly looks good though.

2017-07-05 11:59 UTC, brendo requested changes
Please update the README with the new property and explaining how to use it :)

Tested locally, works as advertised.

2017-07-05 11:59 UTC, brendo commented on package.json
> -    "react-addons-create-fragment": "^15.5.4",
Thank you for removing this!

2017-07-05 11:59 UTC, brendo commented on src/entries/demo/Demo.js
> +    const initialSchemaTreeDepth = 1
This is quite the mouthful! I couldn't think of anything more succinct though :(

2017-07-05 23:56 UTC, quangkhoa commented on src/entries/demo/Demo.js
> +    const initialSchemaTreeDepth = 1
Lol. I can't think of a better one. Potentially we will also have `initialJsonTreeDepth`.

2017-07-06 02:40 UTC, brendo approved these changes

2017-07-06 02:40 UTC, merged