Improve README/CONTRIBUTING. Closes #159
temando/open-api-renderer pull request #163
Opened 2017-07-06 08:02 UTC by brendo

This is just a minor tidy-up to split the README for consumers, and CONTRIBUTING for contributors.

2017-07-06 09:53 UTC, nfour requested changes
Nice stuff. Few bits.

2017-07-06 09:53 UTC, nfour commented on README.md
>  Alternatively, you can pass the contents of the definition directory to Lincoln:
*directly

2017-07-06 09:53 UTC, nfour commented on CONTRIBUTING.md
Good stuff

2017-07-06 09:53 UTC, nfour commented on README.md
> +import Lincoln from '../Lincoln'
Shouldn't that be `react-lincoln`?

2017-07-06 09:53 UTC, nfour commented on README.md
>  [![JavaScript Style Guide](https://img.shields.io/badge/code_style-standard-brightgreen.svg)](https://standardjs.com)
Add npm badge too?

```md
[![NPM](https://img.shields.io/npm/v/react-lincoln.svg)](https://npmjs.org/packages/react-lincoln/)
```

Also may want to grab that package name on npm asap.

2017-07-06 10:46 UTC, brendo commented on README.md
> +import Lincoln from '../Lincoln'
Yep!

2017-07-06 10:46 UTC, brendo commented on README.md
>  Alternatively, you can pass the contents of the definition directory to Lincoln:
ty

2017-07-06 10:48 UTC, brendo commented on README.md
>  [![JavaScript Style Guide](https://img.shields.io/badge/code_style-standard-brightgreen.svg)](https://standardjs.com)
Done, will nab package name tonight/tomorrow.

2017-07-07 00:39 UTC, nfour approved these changes

2017-07-07 00:39 UTC, merged