[WIP] handle servers functionality
temando/open-api-renderer pull request #175
Opened 2017-07-13 05:02 UTC by quangkhoa

2017-07-13 05:24 UTC, brendo requested changes

2017-07-13 05:24 UTC, brendo commented on src/components/Method/Method.js
> +            <MethodPath type={type} path={path} paths={paths} classes={classes}/>
No need to push classes down. Any relevant classes should be moved to the MethodPath component instead.

2017-07-13 05:24 UTC, brendo commented on src/components/Servers/Servers.js
> +          return (
this is all sugar, you can just map directly to `<Server...>` (implicit return)

2017-07-13 05:24 UTC, brendo commented on src/parser/open-api/v3/navigationParser.js
> +      return {
As above, can dump this line and 66 :)

2017-07-13 09:47 UTC, brendo commented on src/parser/open-api/v3/navigationParser.js
> +        description: server.description
This will result in there always being a description property, even if it's `undefined`. I'm not sure if that's desired or not?

2017-07-14 04:53 UTC, quangkhoa commented on src/components/Method/Method.js
> +            <MethodPath type={type} path={path} paths={paths} classes={classes}/>
fixed

2017-07-14 04:56 UTC, quangkhoa commented on src/components/Servers/Servers.js
> +          return (
removed returned statement

2017-07-14 04:57 UTC, quangkhoa commented on src/parser/open-api/v3/navigationParser.js
> +      return {
fixed

2017-07-14 05:28 UTC, quangkhoa commented on src/parser/open-api/v3/navigationParser.js
> +        description: server.description
It's not desired. I've updated the code to not include `description` when it doesn't exist.

2017-07-14 05:47 UTC, brendo approved these changes

2017-07-14 06:09 UTC, merged