Issue 176 handle circular reference in schema
temando/open-api-renderer pull request #187
Opened 2017-07-19 03:18 UTC by quangkhoa

Resolves #176 

I'm not quite happy with the solution. Will need to come back and address how the UI will look like and update the parser accordingly (probably should happen after the parser is refactored). With this change, the user can at least view a schema with circular references, and can see whether an element has circular reference.

2017-07-21 04:26 UTC, brendo requested changes

2017-07-21 04:26 UTC, brendo commented on src/parser/open-api/oneOfResolver.js
> +          walk(obj[key], currentPath)
`obj[key]` can be `item` here too :)

2017-07-21 04:26 UTC, brendo commented on src/parser/open-api/allOfResolver.js
> +const checkedNodes = new Map()
Consider a [`Set`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Set) instead if you just want to track existence of items.

2017-07-21 04:26 UTC, brendo commented on src/parser/open-api/oneOfResolver.js
> +  const checkedNodes = new Map()
Same deal as above, it looks like we don't care about the value here, so consider a `Set`.

2017-07-21 04:26 UTC, brendo commented on src/parser/open-api/schemaParser.js
> +  uiProperty.description = `Circular reference found in **${name}**. Visited nodes: ${visitedNodes}`
I don't think `visitedNodes` adds any value to the user.

eg. 

```
Circular reference found in **categories**. Visited nodes: added, elements, programme, images, initial_children, images, labels, master_brand, titles, next_broadcast, related_links, suppliers, synopses, labels, suppliers, synopses, atoz_programmes, broadcasts, channel, elements, duration, categories.
```

How does the list of nodes help me know what this object should be?

2017-07-21 04:26 UTC, brendo commented on src/parser/open-api/schemaParser.js
> +  uiProperty.description = `Circular reference found in **${name}**. Visited nodes: ${visitedNodes}`
I also find the "found in" part a little confusing. It's more saying, "I have seen this schema before in "categories"".

2017-07-26 07:11 UTC, quangkhoa commented
@brendo I've redone the solution. It should be simpler now.

2017-07-26 08:09 UTC, brendo approved these changes

2017-07-26 08:26 UTC, merged