Feature security schema per method
temando/open-api-renderer pull request #191
Opened 2017-08-30 00:03 UTC by Jonathan-Fan

| Q                       | A   |
| ---                     | --- |
| Bug fix?                | no |
| New feature?            | yes |
| BC breaks?              | yes |
| Deprecations?           | no |
| Continuous improvement? | yes |
| Tests pass?             | yes |
| Changelog updated?      | yes |
| Fixed issue           | [Issue-115](https://github.com/temando/open-api-renderer/issues/115) |

Features:

 * Visualise per method the security schemes required

2017-08-30 05:03 UTC, brendo requested changes
Thanks @Jonathan-Fan! This is mostly pretty good. I previewed it using the Petstore schema though and noticed that it's now quite "heavy" and repetitive.  

What do you think about having an Authentication header and name of the security scheme which links back up to the description at the top of the page?

2017-08-30 05:03 UTC, brendo commented on test/components/__snapshots__/SecurityContainer.test.js.snap
> +  <div
Could you please update these tests with the `placedIn` prop so the snapshot doesn't change?

2017-08-30 05:03 UTC, brendo commented on src/components/SecurityContainer/SecurityContainer.js
> +  placedIn: PropTypes.string
Consider making this propType an enum with the two values we know about. Will help others understand the codebase faster.

2017-08-31 07:08 UTC, Jonathan-Fan commented on src/components/SecurityContainer/SecurityContainer.js
> +  placedIn: PropTypes.string
Changed to `oneOf`.

2017-08-31 07:09 UTC, Jonathan-Fan commented on test/components/__snapshots__/SecurityContainer.test.js.snap
> +  <div
Added `placedIn`, but snapshot still changes since introduce `simple` className.

2017-08-31 07:17 UTC, Jonathan-Fan commented
Regarding to `Authentication Schema`, I think it is a little bit annoying when you check a method and have to jump to the top check the Authentication and then jump back. So in my opinion, we can show/hide the `Authentication Section` for each method.

2017-08-31 07:20 UTC, brendo commented
That too would also be fine. By default it'd be collapsed?

Authentication: authName

2017-12-20 07:52 UTC, Szasza commented
@Jonathan-Fan thank you for getting the implementation this far.

Would it be possible to make the changes @brendo has asked and get this feature merged in?

Thank you in advance for the response.

2017-12-21 04:42 UTC, Jonathan-Fan commented
Hi @Szasza , 
So busy these days,  will do it during Xmas time. 

Regards
Jonathan

2017-12-21 07:48 UTC, Szasza commented
Hi @Jonathan-Fan ,

Thank you for the response, it is much appreciated :)

Kind regards,
Szasza

2018-01-15 04:30 UTC, brendo approved these changes

2018-01-15 04:31 UTC, merged

2018-01-15 05:13 UTC, Szasza commented
:fireworks:

2018-01-15 05:29 UTC, brendo commented
This is now deployed as part of `v0.4.0`